M48
; DRILL file {KiCad (6.0.9)} date Wed Mar  6 21:09:08 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-06T21:09:08-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.9843Y-3.4606
X4.9843Y-4.7992
X6.3228Y-3.4606
X6.3228Y-4.7992
T0
M30
