M48
; DRILL file {KiCad (6.0.9)} date Sun Apr 16 20:23:56 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-16T20:23:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X6.2008Y-2.8701
X6.2008Y-4.2087
X7.5394Y-2.8701
X7.5394Y-4.2087
T0
M30
